on:
  repository_dispatch:
    types:
      - deploy-command

jobs:
  steps:
    - name: testing
      run: |
        echo "Branch: ${{ github.event.client_payload.slash_command.args.named.branch }}"
        echo "Environment: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}"
