on:
  repository_dispatch:
    types:
      - deploy-command

jobs:
  deploy_command:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
      - name: testing
        run: |
          echo "Branch: ${{ github.event.client_payload.slash_command.args.named.branch }}"
          echo "Environment: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}"
